name: CD2 - Deploiement Self-Hosted Runner

on:
  workflow_run:
    workflows: ["CD1 - Deploiement GitHub Pages"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation nginx
        run: |
          choco install nginx -y
        shell: powershell

      - name: Déploiement du site
        run: |
          Copy-Item index.html "C:\tools\nginx\html\index.html" -Force
        shell: powershell

      - name: Démarrage nginx
        run: |
          Start-Process "C:\tools\nginx\nginx.exe"
        shell: powershell
