name: CD2 - Deploiement Self-Hosted Runner

on:
  push:
    branches: [ "PRO" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Lancer le serveur et tester avec curl
        shell: powershell
        run: |
          echo "Démarrage du serveur web..."
          Start-Process -NoNewWindow -FilePath "python" -ArgumentList "-m http.server 8000"
          Start-Sleep -Seconds 3
          echo "Test de la connexion avec curl :"
          curl.exe http://localhost:8000
